### ISSUE TITLE
Bad structure

### ISSUE THREAD

**Issue by Berserker66** [Berserker66/omnitool#15]
Omnitool currently has two forms of bad structure. For one the files are layed out all over the place and should be stuck into proper folders, instead of root.

Secondly, some functions are where they should probably not go and some modules could use a rename. Especially omnitool.py itself should have a lot of stuff outsourced.

For the latter I also propose to move the always needed stuff, like "lang" (currently loaded language), theme and other globals to a globals.py

**Comment by flying-sheep** [comment]
i’ll see what i can do :smile: 

unrelated: you’re a beast! churning out all those commits in the last hours: respect! :bow:

**Comment by Berserker66** [comment]
Ok, so that we won't do the same thing each, I pushed what I did so far in e5f5050c907e1f12c3ecd5388765ac25879b29ff.
It's far from done, though.

**Comment by flying-sheep** [comment]
yeah, looks much better now :)
