### ISSUE TITLE
TROJAN HORSE

### ISSUE THREAD

**Issue by ElTorodeAmor** [Berserker66/omnitool#26]
This program immediately tried to install 6 trojans on my computer. Do not download.

**Comment by Berserker66** [comment]
It doesn't.
The only internet connection it opens is to dropbox to look for updates.
edit:
which is a <1kb json file, containing strings and integer that are used to determine if the version is outdated, if so, Omnitool will hard-coded link to the Github Releases Page.

**Comment by Ijwu** [comment]
@ElTorodeAmor You may want to consider that your computer may simply have trojans on it.

**Comment by ElTorodeAmor** [comment]
Sure. I got six simultaneous Trojan alerts the instant I pressed install on
this. They were probably just waiting you're right.

**Comment by flying-sheep** [comment]
@ElTorodeAmor maybe you got it from a bad page that really added a virus to it.

Also, why 6? Shouldn’t it be one alert?

Can you paste the names of the alleged trojans here?

**Comment by ElTorodeAmor** [comment]
Sure thing. Hopefully this helps.

![image](https://cloud.githubusercontent.com/assets/20544976/22130465/073768ae-de61-11e6-853e-cfccd9b8d7d9.png)

![image](https://cloud.githubusercontent.com/assets/20544976/22130497/3e096ecc-de61-11e6-9e31-9618cb12e73c.png)

**Comment by ElTorodeAmor** [comment]
Sure thing. Hope this helps. I'd like to be able to use this program.

![image](https://cloud.githubusercontent.com/assets/20544976/22130542/7b556880-de61-11e6-89af-42545a0fcf4b.png)
![image](https://cloud.githubusercontent.com/assets/20544976/22130547/88e6b378-de61-11e6-85cd-22bfd146ba8c.png)

**Comment by Berserker66** [comment]
The .PYD files are nothing more than .dll files with a bit more dynamic to them.
They could easily be infected by malware that is already running, just using the pyd as container.
Your Softwareupdater.exe would appear to have done that to them.
Some of those pyd files aren't even by me, they're publicly used on millions of machines; such as numpy.

I did check the pyds on my computer now, and they're clean here.

**Comment by ElTorodeAmor** [comment]
I attempted to reinstall it, I received the exact same quarantine alerts. And the program has yet to successfully launch. Could I have downloaded a corrupted file from github?

**Comment by Berserker66** [comment]
Well, pretty sure github has it's own virus scanner anyway, as when I upload files it takes a while to "validate and check" files. So, either you still have malware running, you didn't get it off github or something quite odd is going on.

Does it detect any .PYD as a virus? Maybe some heuristic is going nuts.

PS:
Try installing 64Bit version, malware usually is still 32bit and cannot infect 64bit DLLs.

**Comment by Berserker66** [comment]
Oh, if someone enters the name of the alleged trojan and pyd into google, one finds that several programs have this issue in their bug tracker, where Norton false positives several python programs.
Case closed, it's norton beeing norton again. sigh
