### ISSUE TITLE
cross platform support

### ISSUE THREAD

**Issue by flying-sheep** [Berserker66/omnitool#9]
terraria 1.3 runs on linux, and so should this.

**Comment by Berserker66** [comment]
agreed, and it already does. The only thing that needs to happen is add linux to the build script and integrate the terraria linux world paths.

More difficult will be mac, as I have no test system.

**Comment by Berserker66** [comment]
For the impatient; you can put the source code into the windows version's folder and run omnitool.py on python3. If you have missing modules (ImportError), simply run "pip install -r requirements.txt" or "python3 -m pip install -r requirements.txt" for the requirements.txt file included with source.

**Comment by flying-sheep** [comment]
it would be great to separate the platform-specific parts, the runtime parts and the build-time parts.

right now, everything is in the root directory:
- the python module (`__init__.py` and other python files)
- inno setup scripts (`.iss` files)
- other install scripts (`zipbuilder.py` and more)
- helpful docs (`world.txt`)
- icons
- build batch scripts (`.bat`)

i propose to move everything that’s needed at runtime into subdirectory (i.e. all `.py` files that import each other at runtime become a module), and creating a `setup.py` which is able to install everything on any OS.

the setup.py would handle the module being installed, data files (they go into `/usr/share/<appname>` on linux), and lauchers (an .exe for windows, a .desktop into `/usr/share/applications` on linux)

so on linux, `python setup.py install` should end up as
- `/usr/lib/python3.4/site-packages/omnitool/*.py`
- `/usr/share/applications/omnitool.desktop`
- `/usr/share/icons/omnitool.png`
- `/usr/share/omnitool/themes/*` (and so on)

and on windows, it should either create a single .exe or install everything into `C:\Program Files\omnitool\`, except the module, which will end up in `C:\Python34\Lib\site-packages`

**Comment by Berserker66** [comment]
Yeah, that would be nice. But disitributing as source on linux may be harder than that. For one, Omnitool uses a modified version of the discontinued PGU module. If the standard one is installed to site-packages random issues may crop up. The other issue, is that the Terraria textures are bundled with the application. Back in the day I got permission to do that, but that permission does not extend to putting those files on the github tracker.

To distribute as source, I'd need to make sure that my pgu_override module always works and I'd need to extract Terraria textures from the installed Terraria on first launch.
So, for now, it's easier to just freeze Omnitool using cx_Freeze for all platforms and distributing as a complete package. This should make it easier to install for the end user as well.

Later, I'm not against including a proper installation from source.

Also I don't think there currently is a module for extracting XNA textures for python currently, at least I don't know of one. The only Tool I do know of is a windows .exe application and I can't really bundle that with the linux source version for texture extraction. In worst case I'd need to write an entire application myself just to do that on all platforms.

**Comment by flying-sheep** [comment]
> For one, Omnitool uses a modified version of the discontinued PGU module. If the standard one is installed to site-packages random issues may crop up.

leave it as submodule and switch to relative imports, problem solved:

```
from .pgu import foobar
```

> the Terraria textures are bundled with the application […]

yeah, in the long run we should extract them from the installation, but that really is a problem.

maybe we can use [fesh0r/xnb_parse](//github.com/fesh0r/xnb_parse)?

---

still, properly separating the module and build scripts are a good thing to do right now :smile:

**Comment by Berserker66** [comment]
Yeah, the separation needs to happen and also elimination of the absolute paths in the setup files.
As for the textures, it may be acceptable to upload them as a passworded zip and download them on first start if not installed already. 

In the long run, see Issue #8 , I want to get rid of PGU anyway.

**Comment by flying-sheep** [comment]
> As for the textures, it may be acceptable to upload them as a passworded zip and download them on first start if not installed already. 

orr, as said, use that module to extract them.

[doesn’t look hard to use](https://github.com/fesh0r/xnb_parse/blob/eb8cfe2ed8532f88f50fe3d8a4b29fa5c79440ec/xnb_parse/read_xnb_dir.py#L15-L23)

**Comment by Berserker66** [comment]
Well, I've hit a blocker - the Terraria linux beta crashes on my Ubuntu before I can even get to the main menu. 
Meanwhile, Omnitool works with the exception of the pgu gui override not working correctly with window resizes, so I can start fixing that.

**Comment by flying-sheep** [comment]
> the Terraria linux beta crashes on my Ubuntu before I can even get to the main menu. 

:cry: that’s sad. on my laptop, same story, but on my desktop it works fine (except for audio issues)

i’m not here this weekend, but if i can help, tell me where :smile: python 3 is my favourite language, and terraria currently the only game i play, so it would be fitting.

**Comment by flying-sheep** [comment]
oh, and where do i find that “modified version of the discontinued PGU module”?

it’s not on git…

**Comment by Berserker66** [comment]
Here's the version maintained by someone else, that my modification is based on:
http://code.google.com/p/pgu/
My modifcation is applied by the pgu_override.py file in the root folder of Omnitool's git.

**Comment by flying-sheep** [comment]
ah, got it. so it’s not a fork, but a monkeypatch :smile:

**Comment by Berserker66** [comment]
My modification really just adds basic handling of the window resize event, a basic command queue hack and a fix to the file dialog window. But yes, not a proper fork at all.

**Comment by Berserker66** [comment]
So, on my Ubuntu VM I've run into an issue, not sure if it also happens in a real system.. I need to reinstall mine sometime - anyway, more testing needed.

When launching a plugin, such as a world generator. It starts inside the main window instead of it's new window. Moments later, this lovely error crashes the program:

```
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 33 requests (33 known processed) with 0 events remaining.
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3.4: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```

Tried fixing it in e0a960917facad100e21d3066c2927596b66c7e7, but persists.

**Comment by Berserker66** [comment]
Launching the plugin directly does work. So it appears to be some compatibility issue with the Python multiprocessing system. A workaround would be to binary freeze each plugin for the linux version, but that is rather awkward for third party plugin programmers, as they'd need to freeze theirs too.
So hopefully I can find another solution.

**Comment by Berserker66** [comment]
Fixed GUI crashes in 1b3346a33241ceaf740d8e6ff81ce5c67d02593a.
So now all this works:
![omnitool ubuntu](https://cloud.githubusercontent.com/assets/3189725/9019754/52d86cee-37f1-11e5-8b0c-b2ff155fb8a0.png)

Only thing not working for me now is cx-freeze build on python3 and Terraria itself.

**Comment by Berserker66** [comment]
It appears, in the source version everything works. However, when frozen with cx-freeze child processes cannot spawn. There is no exception, no text output, no anything - it just doesn't happen.

Unless I can fix the source of that problem, I'm looking at two workarounds:
Use the plugin:launch system to launch the child processes.
Or
Disitribute in source on linux.

**Comment by Berserker66** [comment]
Well, we can't test the linking of tedit at this point, as that simply doesn't exist for linux.

Other than that, once I figure out the cx-freeze issues, everything's set?

**Comment by flying-sheep** [comment]
i didn’t test most functions, so i’ll do that now, and then we can say it is :)

**Comment by Berserker66** [comment]
That has some time, you don't need to rush I'm fairly busy till monday and certainly won't release till monday evening.

**Comment by Berserker66** [comment]
Well I can't get cx-freeze to behave with multiprocessing. After several hours, no tangible progress.
So I think, the best option is to use the "directly launch into a plugin" functionality with os.system() to manually launch new processes.
However, the main mapping is also multiprocessing and that simply doesn't work as separate process..

**Comment by flying-sheep** [comment]
python and paralllelism…

is it really necessary to have multiple processes? isn’t asyncio sufficient?

**Comment by Berserker66** [comment]
It actually does use multiple cpu cores and so far has worked rather well.

It should be possible to keep the world gens and worldrender as separate processes, as they need no syncing with the main one.
The main problem is the mapping. Could use threading there, but that makes it rather slow for a large amount of worlds. If nothing else works, that'll have to do though.
What annoys me is that it works in source just fine, it's just cx-freeze screwing up.
Before giving up I'll look into other freezing methods and maybe I can find something satisfactory.

PS: Asyncio does not work here at all, as all the threads/processes actually have work to do, so no waiting will happen. - It's not IO threading, so asyncIO does not help.

**Comment by flying-sheep** [comment]
well, the only problem with source deploy on linux is the shipped textures, right?

and there is that module i linked that can read XNA resource files, right?

so why not switch to that and deploy via source?

**Comment by flying-sheep** [comment]
also are you aware of [this](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support)?

/edit: yes you are. hmm.

**Comment by Berserker66** [comment]
There's also the problem of having to compile pygame for python 3, with ~30 MB of dependencies. svn module, mercury module. and then pip3, which also doesn't come preinstalled.
It's a rather long list of things. If everything works perfectly, that's still 5-7 console commands with sudo.
When distributing as proper frozen program, no su needed and no tinkering with console needed. You just download and launch. And that's the convenience I want to provide,

It may be possible to provide a setup script of sorts that tries to install all of that. But I have no idea how to setup something like that, that works for most linux distros.

**Comment by flying-sheep** [comment]
hmm, i just had to do `sudo aura -A python-pygame-hg` and install pgu.

isn’t a `pip install -r requirements.txt` enough if svn and mercurial are installed?

**Comment by Berserker66** [comment]
unfortunately no. on ubuntu you also have to do `sudo apt-get install python3-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev   libsdl1.2-dev libsmpeg-dev python-numpy subversion libportmidi-dev ffmpeg libswscale-dev libavformat-dev libavcodec-dev`
Because there are 10 or so optional pygame modules, of which a lot are needed in omnitool - they aren't automatically aquired by pip.
edit: there is a pre built package for pygame on apt-get, but not for python3

**Comment by Berserker66** [comment]
Apparently `apt-get build-dep python3-pygame`should also work. But that's again just debian based.

**Comment by flying-sheep** [comment]
>  there is a pre built package for pygame on apt-get, but not for python3

yeah, as for arch: therefore i got it from the user repository (AUR).

> Because there are 10 or so optional pygame modules, of which a lot are needed in omnitool - they aren't automatically aquired by pip.

we could advise people to do `pip install 'pygame[extras]'`. probably.

> Apparently `apt-get build-dep python-pygame` should also work. But that's again just debian based.

true. we have to see on a case-by-case basis.

**Comment by Berserker66** [comment]
Here's an idea;
We have install instructions for each OS we can cover as .md readmes on git; we link to them inside the main readme. Where applicable also a script/bat that, when given su/admin can acquire everything for that OS.
Then, for an OS we didn't cover, people can figure it out and pull request it in.
To reduce clutter we'd need the folder restructure first though...

Having that should be nice no matter where we go from here.

Short term, though, I'll look over other freezing methods this week - there are plenty out there and I have an unknown amount of time this week.

**Comment by flying-sheep** [comment]
jup, sound good. so i guess this can be closed :smile:

**Comment by Berserker66** [comment]
Oi, just as you closed it, I noticed a new issue. The folder open method currently relies on explorer.exe, so for example "open image folder" doesn't work on non windows.
edit: actually it should not - for some reason though, on ubuntu it tries to call explorer.exe - I'll need to look more into it.

**Comment by flying-sheep** [comment]
the terraria launch function still uses `start`. maybe what is currently called [`open_dir`](https://github.com/Berserker66/omnitool/blob/master/omnitool.py#L765) will also work on urls?

**Comment by Berserker66** [comment]
open_dir won't, but webbrowser.open will. Changed in 7b3bcf843db9998a98b9b7cafecc91331663965f
webbrowser.open is a bit badly named. It actually opens an uri via whatever the OS has to offer. Works on files, networks, urls, programs...
